### ISSUE TITLE
Migración de Imágenes a Firebase

### ISSUE THREAD

**Issue by guillepinto** [software2uis/msv-catalogo#11]
**Como usuario**, quiero que las imágenes de los productos estén almacenadas en **Firebase** en lugar de **Amazon S3**, para asegurar que el sistema de almacenamiento esté alineado con la infraestructura actual.

**Criterios de Aceptación:**
- Las imágenes de los productos deben estar migradas y almacenadas en **Firebase Storage**.
- El sistema debe actualizar correctamente las URLs de las imágenes para que apunten a Firebase.
- No debe haber interrupciones en la visualización de las imágenes durante o después de la migración.

**Comment by Gabriel2152675** [comment]
Realizado, en espera de mas artículos

**Comment by Gabriel2152675** [comment]
Se realiza la actualizacion de nuevos productos con sus respectivas imagenes montadas a firebase y enlazadas a la base de datos
