### ISSUE TITLE
Proveer sugerencias de productos para autocompletar en la barra de búsqueda

### ISSUE THREAD

**Issue by guillepinto** [software2uis/msv-catalogo#12]
**Como** microservicio de catálogo, **quiero** proveer una API que devuelva sugerencias de productos basadas en las entradas parciales del usuario, **para** permitir que el frontend implemente una funcionalidad de autocompletar en la barra de búsqueda.

**Criterios de aceptación:**
- El microservicio debe contar con un endpoint que reciba una cadena parcial como parámetro de búsqueda.
- El microservicio debe devolver un máximo de 5 productos relevantes que coincidan parcialmente con el término de búsqueda.
- Las sugerencias deben basarse en coincidencias de nombre de producto y estar ordenadas por relevancia (ej. popularidad o frecuencia de búsqueda).
- El microservicio debe manejar correctamente las solicitudes vacías o sin coincidencias devolviendo un array vacío.
- La comunicación con el frontend debe hacerse a través de JSON.

**Comment by CarlosGarcia0006** [comment]
completed
